apiVersion: v1
kind: Service
metadata:
    namespace: example
    labels:
        app: crawl
    name: crawl-service
spec:
    ports:
        - port: 5001
          targetPort: 5001
          protocol: TCP
          nodeport: 5001
    selector:
        app: crawl
    type: ClusterIP
    clusterIP: 10.109.2.55
---
apiVersion: v1
kind: Service
metadata:
    namespace: example
    labels:
        app: linebot
    name: linebot-service
spec:
    ports:
        - port: 5002
          targetPort: 5002
          nodeport: 5002
          protocol: TCP
    selector:
        app: linebot
    type: LoadBalancer
    clusterIP: 10.99.230.19

---
apiVersion: v1
kind: Service
metadata:
    namespace: example
    labels:
        app: ticket
    name: ticket-service
spec:
    ports:
        - port: 5003
          targetPort: 5000
          nodeport: 5003
          protocol: TCP
    selector:
        app: ticket
    type: ClusterIP
    ClusterIP: 10.108.42.106

